export const CONST_EXIBIR_CARRINHO = 'EXIBIR'
export const CONST_EXIBIR_PRODUTOS = 'EXIBIR_PRODUTOS'
export const CONST_ATUALIZAR_QUANTIDADE = 'ATUALIZAR_QUANTIDADE'

/*CONSTANTES LOCAL STORAGE*/
export const CONST_DADOS_FILIAL = 'dadosFilial'

/*CONSTANTES CODIGO DE ERRO*/
export const CONST_SEM_ERROS = 0
export const CONST_ERRO_EFAULT = 1